// <auto-generated />
using System;
using AdsoLabs.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdsoLabs.Infrastructure.Migrations
{
    [DbContext(typeof(AdsoDbContext))]
    [Migration("20260308232207_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.AprendizPerfil", b =>
                {
                    b.Property<int>("IdAprendiz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_aprendiz");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAprendiz"));

                    b.Property<string>("CondicionEspecial")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("condicion_especial");

                    b.Property<string>("ContactoEmergenciaNombre")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("contacto_emergencia_nombre");

                    b.Property<string>("ContactoEmergenciaTelefono")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("contacto_emergencia_telefono");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<byte?>("Estrato")
                        .HasColumnType("tinyint")
                        .HasColumnName("estrato");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("sysdatetime()");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("TipoPoblacion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("tipo_poblacion");

                    b.HasKey("IdAprendiz");

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.HasIndex("IdUsuario")
                        .IsUnique()
                        .HasFilter("[id_usuario] IS NOT NULL");

                    b.ToTable("AprendizPerfil", "adso", t =>
                        {
                            t.HasCheckConstraint("CK_Aprendiz_estado", "estado IN ('Activo','Retirado','Aplazado')");

                            t.HasCheckConstraint("CK_Aprendiz_estrato", "estrato BETWEEN 0 AND 6");
                        });
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Archivo", b =>
                {
                    b.Property<int>("IdArchivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_archivo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArchivo"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("DriveId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("drive_id");

                    b.Property<string>("ExtensionArchivo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("extension_archivo");

                    b.Property<DateTime>("FechaSubida")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_subida")
                        .HasDefaultValueSql("sysdatetime()");

                    b.Property<int>("IdTipoArchivo")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_archivo");

                    b.Property<int>("IdUsuarioSubio")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_subio");

                    b.Property<string>("ItemId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("item_id");

                    b.Property<string>("MimeType")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("mime_type");

                    b.Property<string>("NombreAlmacenado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre_almacenado");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre_original");

                    b.Property<string>("RutaStorage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ruta_storage");

                    b.Property<string>("SiteId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("site_id");

                    b.Property<long?>("TamanioBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanio_bytes");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.Property<string>("WebUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("web_url");

                    b.HasKey("IdArchivo");

                    b.HasIndex("IdUsuarioSubio");

                    b.HasIndex("IdTipoArchivo", "FechaSubida")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Archivo_Tipo_Fecha");

                    b.ToTable("Archivo", "adso");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Asistencia", b =>
                {
                    b.Property<int>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_asistencia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsistencia"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("estado");

                    b.Property<int>("IdAprendiz")
                        .HasColumnType("int")
                        .HasColumnName("id_aprendiz");

                    b.Property<int>("IdSesion")
                        .HasColumnType("int")
                        .HasColumnName("id_sesion");

                    b.Property<bool>("Justificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("justificado");

                    b.Property<string>("MotivoInasistencia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("motivo_inasistencia");

                    b.HasKey("IdAsistencia");

                    b.HasIndex("IdAprendiz")
                        .HasDatabaseName("IX_Asistencia_Aprendiz");

                    b.HasIndex("IdSesion", "IdAprendiz")
                        .IsUnique()
                        .HasDatabaseName("UQ_Asistencia");

                    b.ToTable("Asistencia", "adso", t =>
                        {
                            t.HasCheckConstraint("CK_Asistencia_estado", "estado IN ('Presente','Ausente')");
                        });
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Auditoria", b =>
                {
                    b.Property<long>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_auditoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdAuditoria"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("accion");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("datos_nuevos");

                    b.Property<string>("DatosViejos")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("datos_viejos");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("direccion_ip");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("sysdatetime()");

                    b.Property<string>("IdRegistroAfectado")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("id_registro_afectado");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("tabla_afectada");

                    b.HasKey("IdAuditoria");

                    b.ToTable("Auditoria", "adso");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Competencia", b =>
                {
                    b.Property<int>("IdCompetencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_competencia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompetencia"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<int>("HorasAsignadas")
                        .HasColumnType("int")
                        .HasColumnName("horas_asignadas");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasDefaultValue("Tecnica")
                        .HasColumnName("tipo");

                    b.HasKey("IdCompetencia");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Competencia", "adso", t =>
                        {
                            t.HasCheckConstraint("CK_Competencia_horas", "horas_asignadas > 0");

                            t.HasCheckConstraint("CK_Competencia_tipo", "tipo IN ('Tecnica','Transversal','Clave','Induccion','Practica')");
                        });
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.ConfiguracionAlerta", b =>
                {
                    b.Property<int>("IdConfig")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_config");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConfig"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("canal");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_modificacion")
                        .HasDefaultValueSql("sysdatetime()");

                    b.Property<int>("IdUsuarioModifico")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_modifico");

                    b.Property<string>("PlantillaAsunto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("plantilla_asunto");

                    b.Property<string>("PlantillaCuerpo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("plantilla_cuerpo");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_alerta");

                    b.Property<int>("Umbral")
                        .HasColumnType("int")
                        .HasColumnName("umbral");

                    b.HasKey("IdConfig");

                    b.HasIndex("IdUsuarioModifico");

                    b.HasIndex("TipoAlerta")
                        .IsUnique()
                        .HasDatabaseName("UX_CfgAlerta_tipo");

                    b.ToTable("ConfiguracionAlerta", "adso", t =>
                        {
                            t.HasCheckConstraint("CK_CfgAlerta_canal", "canal IN ('email','app','ambos')");
                        });
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.DesarrolloCurricular", b =>
                {
                    b.Property<int>("IdDesarrollo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_desarrollo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDesarrollo"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasDefaultValue("Borrador")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("sysdatetime()");

                    b.Property<int>("IdCompetencia")
                        .HasColumnType("int")
                        .HasColumnName("id_competencia");

                    b.Property<int>("IdDocumento")
                        .HasColumnType("int")
                        .HasColumnName("id_documento");

                    b.Property<int>("IdInstructor")
                        .HasColumnType("int")
                        .HasColumnName("id_instructor");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("IdDesarrollo");

                    b.HasIndex("IdCompetencia")
                        .HasDatabaseName("IX_DesarrolloCurricular_Competencia");

                    b.HasIndex("IdDocumento");

                    b.HasIndex("IdInstructor");

                    b.ToTable("DesarrolloCurricular", "adso", t =>
                        {
                            t.HasCheckConstraint("CK_DesaCurr_estado", "estado IN ('Borrador','Publicado','Cerrado')");
                        });
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Ficha", b =>
                {
                    b.Property<int>("IdFicha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ficha");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFicha"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("sysdatetime()");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroFicha")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("numero_ficha");

                    b.HasKey("IdFicha");

                    b.HasIndex("NumeroFicha")
                        .IsUnique();

                    b.ToTable("Ficha", "adso", t =>
                        {
                            t.HasCheckConstraint("CK_Ficha_estado", "estado IN ('Activa','Finalizada','Suspendida')");
                        });
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.FichaCompetencia", b =>
                {
                    b.Property<int>("IdFichaCompetencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ficha_competencia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFichaCompetencia"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("HorasEjecutadas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("horas_ejecutadas");

                    b.Property<int>("IdCompetencia")
                        .HasColumnType("int")
                        .HasColumnName("id_competencia");

                    b.Property<int>("IdFicha")
                        .HasColumnType("int")
                        .HasColumnName("id_ficha");

                    b.Property<int>("IdInstructor")
                        .HasColumnType("int")
                        .HasColumnName("id_instructor");

                    b.HasKey("IdFichaCompetencia");

                    b.HasIndex("IdCompetencia");

                    b.HasIndex("IdFicha", "IdCompetencia")
                        .IsUnique()
                        .HasDatabaseName("UX_FC_Ficha_Competencia");

                    b.HasIndex("IdInstructor", "FechaInicio", "FechaFin")
                        .HasDatabaseName("IX_FC_Instructor_Fecha");

                    b.ToTable("FichaCompetencia", "adso", t =>
                        {
                            t.HasCheckConstraint("CK_FC_estado", "estado IN ('Pendiente','En curso','Finalizada')");
                        });
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.GuiaAprendizaje", b =>
                {
                    b.Property<int>("IdGuia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_guia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGuia"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasDefaultValue("Borrador")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("sysdatetime()");

                    b.Property<int>("IdDocumento")
                        .HasColumnType("int")
                        .HasColumnName("id_documento");

                    b.Property<int>("IdFichaCompetencia")
                        .HasColumnType("int")
                        .HasColumnName("id_ficha_competencia");

                    b.Property<int>("IdInstructor")
                        .HasColumnType("int")
                        .HasColumnName("id_instructor");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("titulo");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("IdGuia");

                    b.HasIndex("IdDocumento");

                    b.HasIndex("IdFichaCompetencia")
                        .HasDatabaseName("IX_GuiaAprendizaje_FC");

                    b.HasIndex("IdInstructor");

                    b.ToTable("GuiaAprendizaje", "adso", t =>
                        {
                            t.HasCheckConstraint("CK_Guia_estado", "estado IN ('Borrador','Publicado','Cerrado')");
                        });
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.ImportacionArchivo", b =>
                {
                    b.Property<int>("IdImportacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_importacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImportacion"));

                    b.Property<string>("EstadoProcesamiento")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("estado_procesamiento");

                    b.Property<DateTime?>("FechaProcesado")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_procesado");

                    b.Property<DateTime>("FechaSubida")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_subida")
                        .HasDefaultValueSql("sysdatetime()");

                    b.Property<int?>("FilasError")
                        .HasColumnType("int")
                        .HasColumnName("filas_error");

                    b.Property<int?>("FilasOk")
                        .HasColumnType("int")
                        .HasColumnName("filas_ok");

                    b.Property<int>("IdDocumento")
                        .HasColumnType("int")
                        .HasColumnName("id_documento");

                    b.Property<int?>("IdSesionDestino")
                        .HasColumnType("int")
                        .HasColumnName("id_sesion_destino");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("observacion");

                    b.Property<string>("TipoEntidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo_entidad");

                    b.Property<int?>("TotalFilas")
                        .HasColumnType("int")
                        .HasColumnName("total_filas");

                    b.HasKey("IdImportacion");

                    b.HasIndex("IdDocumento");

                    b.HasIndex("IdSesionDestino");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("IX_Import_Usuario");

                    b.HasIndex("TipoEntidad", "FechaSubida")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Import_Tipo_Fecha");

                    b.ToTable("ImportacionArchivo", "adso", t =>
                        {
                            t.HasCheckConstraint("CK_Import_estado", "estado_procesamiento IN ('Pendiente','Procesado','Error')");

                            t.HasCheckConstraint("CK_Import_tipo", "tipo_entidad IN ('Aprendiz','Instructor','Ficha','Competencia','FichaCompetencia','Asistencia')");
                        });
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.ImportacionError", b =>
                {
                    b.Property<int>("IdError")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_error");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdError"));

                    b.Property<string>("DatosFila")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("datos_fila");

                    b.Property<int>("IdImportacion")
                        .HasColumnType("int")
                        .HasColumnName("id_importacion");

                    b.Property<string>("MotivoError")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("motivo_error");

                    b.Property<int>("NumeroFila")
                        .HasColumnType("int")
                        .HasColumnName("numero_fila");

                    b.HasKey("IdError");

                    b.HasIndex("IdImportacion")
                        .HasDatabaseName("IX_ImportErr_Importacion");

                    b.ToTable("ImportacionError", "adso");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.InstructorPerfil", b =>
                {
                    b.Property<int>("IdInstructor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_instructor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInstructor"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("especialidad");

                    b.Property<DateOnly?>("FechaVinculacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vinculacion");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("NumeroContrato")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("numero_contrato");

                    b.Property<string>("TipoVinculacion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo_vinculacion");

                    b.HasKey("IdInstructor");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("InstructorPerfil", "adso", t =>
                        {
                            t.HasCheckConstraint("CK_InstrPerfil_vinculacion", "tipo_vinculacion IN ('Planta','Contratista','Provisional')");
                        });
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.InstrumentoEvaluacion", b =>
                {
                    b.Property<int>("IdInstrumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_instrumento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInstrumento"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasDefaultValue("Borrador")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("sysdatetime()");

                    b.Property<int>("IdCompetencia")
                        .HasColumnType("int")
                        .HasColumnName("id_competencia");

                    b.Property<int>("IdDocumento")
                        .HasColumnType("int")
                        .HasColumnName("id_documento");

                    b.Property<int>("IdInstructor")
                        .HasColumnType("int")
                        .HasColumnName("id_instructor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("nombre");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("IdInstrumento");

                    b.HasIndex("IdCompetencia")
                        .HasDatabaseName("IX_InstrumentoEvaluacion_Competencia");

                    b.HasIndex("IdDocumento");

                    b.HasIndex("IdInstructor");

                    b.ToTable("InstrumentoEvaluacion", "adso", t =>
                        {
                            t.HasCheckConstraint("CK_Inst_estado", "estado IN ('Borrador','Publicado','Cerrado')");
                        });
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.JuicioResultado", b =>
                {
                    b.Property<int>("IdJuicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_juicio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJuicio"));

                    b.Property<DateTime?>("FechaJuicio")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_juicio");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("sysdatetime()");

                    b.Property<int>("IdAprendiz")
                        .HasColumnType("int")
                        .HasColumnName("id_aprendiz");

                    b.Property<int>("IdResultado")
                        .HasColumnType("int")
                        .HasColumnName("id_resultado");

                    b.Property<string>("Juicio")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Por Evaluar")
                        .HasColumnName("juicio");

                    b.Property<string>("RegistradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("registrado_por");

                    b.HasKey("IdJuicio");

                    b.HasIndex("IdAprendiz")
                        .HasDatabaseName("IX_JuicioResultado_Aprendiz");

                    b.HasIndex("IdResultado")
                        .HasDatabaseName("IX_JuicioResultado_Resultado");

                    b.HasIndex("IdResultado", "IdAprendiz")
                        .IsUnique()
                        .HasDatabaseName("UQ_Juicio");

                    b.ToTable("JuicioResultado", "adso", t =>
                        {
                            t.HasCheckConstraint("CK_Juicio_juicio", "juicio IN ('Aprobado','No Aprobado','Por Evaluar')");
                        });
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Notificacion", b =>
                {
                    b.Property<long>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_notificacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdNotificacion"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("asunto");

                    b.Property<string>("CanalUsado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("canal_usado");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cuerpo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_envio");

                    b.Property<DateTime>("FechaGeneracion")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_generacion")
                        .HasDefaultValueSql("sysdatetime()");

                    b.Property<int?>("IdDestinatarioUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_destinatario_usuario");

                    b.Property<bool>("Leido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("leido");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_alerta");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("IdDestinatarioUsuario");

                    b.HasIndex("Estado", "FechaGeneracion")
                        .HasDatabaseName("IX_Noti_Estado_Fecha");

                    b.ToTable("Notificacion", "adso", t =>
                        {
                            t.HasCheckConstraint("CK_Noti_estado", "estado IN ('Pendiente','Enviada','Error')");
                        });
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.ObservacionAprendiz", b =>
                {
                    b.Property<long>("IdObservacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_observacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdObservacion"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("sysdatetime()");

                    b.Property<int>("IdAprendiz")
                        .HasColumnType("int")
                        .HasColumnName("id_aprendiz");

                    b.Property<int?>("IdCompetencia")
                        .HasColumnType("int")
                        .HasColumnName("id_competencia");

                    b.Property<int>("IdInstructor")
                        .HasColumnType("int")
                        .HasColumnName("id_instructor");

                    b.Property<int?>("IdSesion")
                        .HasColumnType("int")
                        .HasColumnName("id_sesion");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo");

                    b.HasKey("IdObservacion");

                    b.HasIndex("IdAprendiz");

                    b.HasIndex("IdCompetencia");

                    b.HasIndex("IdInstructor");

                    b.HasIndex("IdSesion");

                    b.ToTable("ObservacionAprendiz", "adso", t =>
                        {
                            t.HasCheckConstraint("CK_Obs_tipo", "tipo IN ('General','Academica','Convivencia','Seguimiento')");
                        });
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("IdToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_token");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdToken"));

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("sysdatetime()");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_expiracion");

                    b.Property<DateTime?>("FechaUso")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_uso");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varbinary(256)")
                        .HasColumnName("token_hash");

                    b.HasKey("IdToken");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("IX_PRT_Usuario");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_PRT_TokenHash");

                    b.ToTable("PasswordResetToken", "adso");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("direccion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("sysdatetime()");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<int>("IdTipoDocumento")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_documento");

                    b.Property<string>("Municipio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("municipio");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("numero_documento");

                    b.Property<string>("Telefono")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("telefono");

                    b.HasKey("IdPersona");

                    b.HasIndex("IdTipoDocumento");

                    b.HasIndex("NumeroDocumento")
                        .IsUnique()
                        .HasDatabaseName("IX_Persona_Documento");

                    b.ToTable("Persona", "adso");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.PlanConcertado", b =>
                {
                    b.Property<int>("IdPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_plan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlan"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("DescripcionGeneral")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Plan de evaluacion concertado con los aprendices de acuerdo con los resultados de aprendizaje de la competencia.")
                        .HasColumnName("descripcion_general");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasDefaultValue("Borrador")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCierre")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_cierre");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("sysdatetime()");

                    b.Property<int>("IdCompetencia")
                        .HasColumnType("int")
                        .HasColumnName("id_competencia");

                    b.Property<int>("IdDocumento")
                        .HasColumnType("int")
                        .HasColumnName("id_documento");

                    b.Property<int>("IdInstructor")
                        .HasColumnType("int")
                        .HasColumnName("id_instructor");

                    b.HasKey("IdPlan");

                    b.HasIndex("IdCompetencia");

                    b.HasIndex("IdDocumento");

                    b.HasIndex("IdInstructor");

                    b.ToTable("PlanConcertado", "adso", t =>
                        {
                            t.HasCheckConstraint("CK_Plan_estado", "estado IN ('Borrador','Publicado','Cerrado')");
                        });
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.PlaneacionPedagogica", b =>
                {
                    b.Property<int>("IdPlaneacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_planeacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlaneacion"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasDefaultValue("Borrador")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("sysdatetime()");

                    b.Property<int>("IdDocumento")
                        .HasColumnType("int")
                        .HasColumnName("id_documento");

                    b.Property<int>("IdFichaCompetencia")
                        .HasColumnType("int")
                        .HasColumnName("id_ficha_competencia");

                    b.Property<int>("IdInstructor")
                        .HasColumnType("int")
                        .HasColumnName("id_instructor");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("IdPlaneacion");

                    b.HasIndex("IdDocumento");

                    b.HasIndex("IdFichaCompetencia")
                        .HasDatabaseName("IX_PlaneacionPedagogica_FC");

                    b.HasIndex("IdInstructor");

                    b.ToTable("PlaneacionPedagogica", "adso", t =>
                        {
                            t.HasCheckConstraint("CK_Planea_estado", "estado IN ('Borrador','Publicado','Cerrado')");
                        });
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.ProyectoFormativo", b =>
                {
                    b.Property<int>("IdProyecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_proyecto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProyecto"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasDefaultValue("Borrador")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("sysdatetime()");

                    b.Property<int>("IdDocumento")
                        .HasColumnType("int")
                        .HasColumnName("id_documento");

                    b.Property<int>("IdFicha")
                        .HasColumnType("int")
                        .HasColumnName("id_ficha");

                    b.Property<int>("IdInstructor")
                        .HasColumnType("int")
                        .HasColumnName("id_instructor");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("titulo");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("IdProyecto");

                    b.HasIndex("IdDocumento");

                    b.HasIndex("IdFicha");

                    b.HasIndex("IdInstructor");

                    b.ToTable("ProyectoFormativo", "adso", t =>
                        {
                            t.HasCheckConstraint("CK_Proy_estado", "estado IN ('Borrador','Publicado','Cerrado')");
                        });
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.ResultadoAprendizaje", b =>
                {
                    b.Property<int>("IdResultado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_resultado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResultado"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("codigo");

                    b.Property<int>("IdPlan")
                        .HasColumnType("int")
                        .HasColumnName("id_plan");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre");

                    b.HasKey("IdResultado");

                    b.HasIndex("IdPlan")
                        .HasDatabaseName("IX_ResultadoAprendizaje_Plan");

                    b.HasIndex("IdPlan", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("UQ_Res_Plan_Codigo");

                    b.ToTable("ResultadoAprendizaje", "adso");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Rol", "adso");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Sesion", b =>
                {
                    b.Property<int>("IdSesion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sesion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSesion"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<TimeOnly>("HoraFin")
                        .HasPrecision(0)
                        .HasColumnType("time(0)")
                        .HasColumnName("hora_fin");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasPrecision(0)
                        .HasColumnType("time(0)")
                        .HasColumnName("hora_inicio");

                    b.Property<int>("IdFichaCompetencia")
                        .HasColumnType("int")
                        .HasColumnName("id_ficha_competencia");

                    b.Property<int>("IdInstructor")
                        .HasColumnType("int")
                        .HasColumnName("id_instructor");

                    b.HasKey("IdSesion");

                    b.HasIndex("IdFichaCompetencia");

                    b.HasIndex("IdInstructor");

                    b.ToTable("Sesion", "adso");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.TipoArchivo", b =>
                {
                    b.Property<int>("IdTipoArchivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_archivo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoArchivo"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdTipoArchivo");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TipoArchivo", "adso");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.TipoDocumento", b =>
                {
                    b.Property<int>("IdTipoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_documento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoDocumento"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nombre");

                    b.HasKey("IdTipoDocumento");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TipoDocumento", "adso");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("bloqueado_hasta");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("correo");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("sysdatetime()");

                    b.Property<DateTime?>("FechaInicioSesion")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_inicio_sesion");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<int>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("intentos_fallidos");

                    b.Property<byte[]>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("varbinary(256)")
                        .HasColumnName("password_hash");

                    b.Property<byte[]>("PasswordSalt")
                        .HasMaxLength(128)
                        .HasColumnType("varbinary(128)")
                        .HasColumnName("password_salt");

                    b.Property<bool>("PrimerLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("primer_login");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuario_Correo");

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.ToTable("Usuario", "adso");
                });

            modelBuilder.Entity("FichaAprendiz", b =>
                {
                    b.Property<int>("id_ficha")
                        .HasColumnType("int");

                    b.Property<int>("id_aprendiz")
                        .HasColumnType("int");

                    b.HasKey("id_ficha", "id_aprendiz");

                    b.HasIndex("id_aprendiz");

                    b.ToTable("FichaAprendiz", "adso");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.AprendizPerfil", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.Persona", "Persona")
                        .WithOne("AprendizPerfil")
                        .HasForeignKey("AdsoLabs.Infrastructure.Entities.AprendizPerfil", "IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AprendizPerfil_Persona");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.Usuario", "Usuario")
                        .WithOne("AprendizPerfil")
                        .HasForeignKey("AdsoLabs.Infrastructure.Entities.AprendizPerfil", "IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_AprendizPerfil_Usuario");

                    b.Navigation("Persona");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Archivo", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.TipoArchivo", "TipoArchivo")
                        .WithMany("Archivos")
                        .HasForeignKey("IdTipoArchivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Archivo_Tipo");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.Usuario", "UsuarioSubio")
                        .WithMany("Archivos")
                        .HasForeignKey("IdUsuarioSubio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Archivo_SubidoPor");

                    b.Navigation("TipoArchivo");

                    b.Navigation("UsuarioSubio");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Asistencia", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.AprendizPerfil", "Aprendiz")
                        .WithMany("Asistencias")
                        .HasForeignKey("IdAprendiz")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Asistencia_Aprendiz");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.Sesion", "Sesion")
                        .WithMany("Asistencias")
                        .HasForeignKey("IdSesion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Asistencia_Sesion");

                    b.Navigation("Aprendiz");

                    b.Navigation("Sesion");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.ConfiguracionAlerta", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.Usuario", "UsuarioModifico")
                        .WithMany("ConfiguracionesAlerta")
                        .HasForeignKey("IdUsuarioModifico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CfgAlerta_Usuario");

                    b.Navigation("UsuarioModifico");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.DesarrolloCurricular", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.Competencia", "Competencia")
                        .WithMany("DesarrollosCurriculares")
                        .HasForeignKey("IdCompetencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DesaCurr_Competencia");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.Archivo", "Documento")
                        .WithMany("DesarrollosCurriculares")
                        .HasForeignKey("IdDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DesaCurr_Archivo");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.InstructorPerfil", "Instructor")
                        .WithMany("DesarrollosCurriculares")
                        .HasForeignKey("IdInstructor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DesaCurr_Instructor");

                    b.Navigation("Competencia");

                    b.Navigation("Documento");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.FichaCompetencia", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.Competencia", "Competencia")
                        .WithMany("FichasCompetencias")
                        .HasForeignKey("IdCompetencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FC_Competencia");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.Ficha", "Ficha")
                        .WithMany("FichasCompetencias")
                        .HasForeignKey("IdFicha")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FC_Ficha");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.InstructorPerfil", "Instructor")
                        .WithMany("FichasCompetencias")
                        .HasForeignKey("IdInstructor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FC_Instructor");

                    b.Navigation("Competencia");

                    b.Navigation("Ficha");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.GuiaAprendizaje", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.Archivo", "Documento")
                        .WithMany("GuiasAprendizaje")
                        .HasForeignKey("IdDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Guia_Archivo");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.FichaCompetencia", "FichaCompetencia")
                        .WithMany("GuiasAprendizaje")
                        .HasForeignKey("IdFichaCompetencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Guia_FC");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.InstructorPerfil", "Instructor")
                        .WithMany("GuiasAprendizaje")
                        .HasForeignKey("IdInstructor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Guia_Instructor");

                    b.Navigation("Documento");

                    b.Navigation("FichaCompetencia");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.ImportacionArchivo", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.Archivo", "Documento")
                        .WithMany("Importaciones")
                        .HasForeignKey("IdDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Import_Archivo");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.Sesion", "SesionDestino")
                        .WithMany("Importaciones")
                        .HasForeignKey("IdSesionDestino")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Import_Sesion");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.Usuario", "Usuario")
                        .WithMany("Importaciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Import_Usuario");

                    b.Navigation("Documento");

                    b.Navigation("SesionDestino");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.ImportacionError", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.ImportacionArchivo", "Importacion")
                        .WithMany("Errores")
                        .HasForeignKey("IdImportacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ImportErr_Import");

                    b.Navigation("Importacion");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.InstructorPerfil", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.Usuario", "Usuario")
                        .WithOne("InstructorPerfil")
                        .HasForeignKey("AdsoLabs.Infrastructure.Entities.InstructorPerfil", "IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_InstrPerfil_Usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.InstrumentoEvaluacion", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.Competencia", "Competencia")
                        .WithMany("InstrumentosEvaluacion")
                        .HasForeignKey("IdCompetencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Inst_Competencia");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.Archivo", "Documento")
                        .WithMany("InstrumentosEvaluacion")
                        .HasForeignKey("IdDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Inst_Archivo");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.InstructorPerfil", "Instructor")
                        .WithMany("InstrumentosEvaluacion")
                        .HasForeignKey("IdInstructor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Inst_Instructor");

                    b.Navigation("Competencia");

                    b.Navigation("Documento");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.JuicioResultado", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.AprendizPerfil", "Aprendiz")
                        .WithMany("JuiciosResultado")
                        .HasForeignKey("IdAprendiz")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Juicio_Aprendiz");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.ResultadoAprendizaje", "Resultado")
                        .WithMany("JuiciosResultado")
                        .HasForeignKey("IdResultado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Juicio_Resultado");

                    b.Navigation("Aprendiz");

                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Notificacion", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.Usuario", "DestinatarioUsuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdDestinatarioUsuario")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Noti_DestUsuario");

                    b.Navigation("DestinatarioUsuario");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.ObservacionAprendiz", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.AprendizPerfil", "Aprendiz")
                        .WithMany("Observaciones")
                        .HasForeignKey("IdAprendiz")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Obs_Aprendiz");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.Competencia", "Competencia")
                        .WithMany("Observaciones")
                        .HasForeignKey("IdCompetencia")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Obs_Competencia");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.InstructorPerfil", "Instructor")
                        .WithMany("Observaciones")
                        .HasForeignKey("IdInstructor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Obs_Instructor");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.Sesion", "Sesion")
                        .WithMany("Observaciones")
                        .HasForeignKey("IdSesion")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Obs_Sesion");

                    b.Navigation("Aprendiz");

                    b.Navigation("Competencia");

                    b.Navigation("Instructor");

                    b.Navigation("Sesion");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.Usuario", "Usuario")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PRT_Usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Persona", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany("Personas")
                        .HasForeignKey("IdTipoDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Persona_TipoDoc");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.PlanConcertado", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.Competencia", "Competencia")
                        .WithMany("PlanesConcertados")
                        .HasForeignKey("IdCompetencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Plan_Competencia");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.Archivo", "Documento")
                        .WithMany("PlanesConcertados")
                        .HasForeignKey("IdDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Plan_Archivo");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.InstructorPerfil", "Instructor")
                        .WithMany("PlanesConcertados")
                        .HasForeignKey("IdInstructor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Plan_Instructor");

                    b.Navigation("Competencia");

                    b.Navigation("Documento");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.PlaneacionPedagogica", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.Archivo", "Documento")
                        .WithMany("PlaneacionesPedagogicas")
                        .HasForeignKey("IdDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Planea_Archivo");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.FichaCompetencia", "FichaCompetencia")
                        .WithMany("PlaneacionesPedagogicas")
                        .HasForeignKey("IdFichaCompetencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Planea_FC");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.InstructorPerfil", "Instructor")
                        .WithMany("PlaneacionesPedagogicas")
                        .HasForeignKey("IdInstructor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Planea_Instructor");

                    b.Navigation("Documento");

                    b.Navigation("FichaCompetencia");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.ProyectoFormativo", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.Archivo", "Documento")
                        .WithMany("ProyectosFormativos")
                        .HasForeignKey("IdDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Proy_Archivo");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.Ficha", "Ficha")
                        .WithMany("ProyectosFormativos")
                        .HasForeignKey("IdFicha")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Proy_Ficha");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.InstructorPerfil", "Instructor")
                        .WithMany("ProyectosFormativos")
                        .HasForeignKey("IdInstructor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Proy_Instructor");

                    b.Navigation("Documento");

                    b.Navigation("Ficha");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.ResultadoAprendizaje", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.PlanConcertado", "Plan")
                        .WithMany("ResultadosAprendizaje")
                        .HasForeignKey("IdPlan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Res_Plan");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Sesion", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.FichaCompetencia", "FichaCompetencia")
                        .WithMany("Sesiones")
                        .HasForeignKey("IdFichaCompetencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Sesion_FC");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.InstructorPerfil", "Instructor")
                        .WithMany("Sesiones")
                        .HasForeignKey("IdInstructor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Sesion_Instructor");

                    b.Navigation("FichaCompetencia");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Usuario", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.Persona", "Persona")
                        .WithOne("Usuario")
                        .HasForeignKey("AdsoLabs.Infrastructure.Entities.Usuario", "IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Persona");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Rol");

                    b.Navigation("Persona");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("FichaAprendiz", b =>
                {
                    b.HasOne("AdsoLabs.Infrastructure.Entities.AprendizPerfil", null)
                        .WithMany()
                        .HasForeignKey("id_aprendiz")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FichaAprendiz_Aprendiz");

                    b.HasOne("AdsoLabs.Infrastructure.Entities.Ficha", null)
                        .WithMany()
                        .HasForeignKey("id_ficha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FichaAprendiz_Ficha");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.AprendizPerfil", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("JuiciosResultado");

                    b.Navigation("Observaciones");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Archivo", b =>
                {
                    b.Navigation("DesarrollosCurriculares");

                    b.Navigation("GuiasAprendizaje");

                    b.Navigation("Importaciones");

                    b.Navigation("InstrumentosEvaluacion");

                    b.Navigation("PlaneacionesPedagogicas");

                    b.Navigation("PlanesConcertados");

                    b.Navigation("ProyectosFormativos");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Competencia", b =>
                {
                    b.Navigation("DesarrollosCurriculares");

                    b.Navigation("FichasCompetencias");

                    b.Navigation("InstrumentosEvaluacion");

                    b.Navigation("Observaciones");

                    b.Navigation("PlanesConcertados");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Ficha", b =>
                {
                    b.Navigation("FichasCompetencias");

                    b.Navigation("ProyectosFormativos");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.FichaCompetencia", b =>
                {
                    b.Navigation("GuiasAprendizaje");

                    b.Navigation("PlaneacionesPedagogicas");

                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.ImportacionArchivo", b =>
                {
                    b.Navigation("Errores");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.InstructorPerfil", b =>
                {
                    b.Navigation("DesarrollosCurriculares");

                    b.Navigation("FichasCompetencias");

                    b.Navigation("GuiasAprendizaje");

                    b.Navigation("InstrumentosEvaluacion");

                    b.Navigation("Observaciones");

                    b.Navigation("PlaneacionesPedagogicas");

                    b.Navigation("PlanesConcertados");

                    b.Navigation("ProyectosFormativos");

                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Persona", b =>
                {
                    b.Navigation("AprendizPerfil");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.PlanConcertado", b =>
                {
                    b.Navigation("ResultadosAprendizaje");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.ResultadoAprendizaje", b =>
                {
                    b.Navigation("JuiciosResultado");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Sesion", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Importaciones");

                    b.Navigation("Observaciones");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.TipoArchivo", b =>
                {
                    b.Navigation("Archivos");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.TipoDocumento", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("AdsoLabs.Infrastructure.Entities.Usuario", b =>
                {
                    b.Navigation("AprendizPerfil");

                    b.Navigation("Archivos");

                    b.Navigation("ConfiguracionesAlerta");

                    b.Navigation("Importaciones");

                    b.Navigation("InstructorPerfil");

                    b.Navigation("Notificaciones");

                    b.Navigation("PasswordResetTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
